---
- name: "Set up Kali Environment"
  hosts: localhost
  roles:
    - install_packages
    - dotfiles
    - setup_burpsuite
    - setup_firefox

  tasks:
    - name: "Reboot"
      ansible.builtin.shell: "nohup -- bash -c 'sleep 3; reboot' &"
      async: 0
      poll: 0
      changed_when: false
