---
- name: "Build Kali Enviroment"
  hosts: localhost
  connection: local
  roles:
    - install_packages
    - setup_shell
    - setup_config
    - setup_burpsuite
    - setup_firefox

  tasks:
    - name: "Finished"
      ansible.builtin.pause:
        prompt: "Kali setup complete. Would you like to reboot the system now? (y/N):"
      register: yn

    - name: "Reboot"
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: yn.user_input == 'y'
