---
- name: "Build Kali Enviroment"
  hosts: localhost
  connection: local
  roles:
    - install_packages
    - setup_shell
    - setup_config
    - setup_burpsuite
    - setup_firefox

  tasks:
    - name: "Finished"
      ansible.builtin.debug:
        msg: |
          Kali was successfully set up, you can remove this folder and reboot the system:
          cd ..; rm -rf kali-setup; reboot
