---
- name: "Set up Kali Environment"
  hosts: localhost
  roles:
    - install_packages
    - setup_dotfiles
    - setup_settings
    - setup_chrome
    - setup_burpsuite

  tasks:
    - name: "Clean up"
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
      become: true

    - name: "Reboot"
      ansible.builtin.shell: "sleep 5; nohup -- reboot &"
      async: 0
      poll: 0
      changed_when: false
