---
- name: "Download dotfiles"
  ansible.builtin.git:
    repo: "https://github.com/NLXZ/dotfiles"
    dest: "$HOME/.dotfiles"
    depth: 1
    version: "main"
    force: true
  become: true
  become_user: "{{ lookup('pipe', 'id -nu 1000') }}"
  tags:
    - dotfiles

- name: "Copy user dotfiles"
  ansible.builtin.shell: |
    rsync -a "$HOME"/.dotfiles/ "$HOME"/
  changed_when: true
  become: true
  become_user: "{{ lookup('pipe', 'id -nu 1000') }}"
  tags:
    - dotfiles

- name: "Copy root dotfiles"
  ansible.builtin.shell: |
    rsync -a /home/{{ lookup('pipe', 'id -nu 1000') }}/.dotfiles/ "$HOME"/
  changed_when: true
  tags:
    - dotfiles

- name: "Install neovim plugins"
  ansible.builtin.shell: |
    set -o pipefail
    cmd='nvim --headless -c "autocmd User PackerComplete quitall" -c "PackerSync"'
    sudo -- su {{ lookup('pipe', 'id -nu 1000') }} -c "$cmd"
    sudo -- su root -c "$cmd"
    sudo update-alternatives --quiet --set vi /usr/bin/nvim
  changed_when: true
  tags:
    - dotfiles

- name: "Install nerd fonts"
  ansible.builtin.shell: |
    set -o pipefail
    curl -sfLo /tmp/JetBrainsMono.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    sudo unzip -oq /tmp/JetBrainsMono.zip -d /usr/share/fonts/JetBrainsMonoNF
    sudo fc-cache -fv
  changed_when: true
  tags:
    - dotfiles
