---
- name: "Clone dotfiles"
  ansible.builtin.git:
    repo: "https://github.com/NLXZ/dotfiles.git"
    dest: "/tmp/dotfiles"
    clone: "yes"
    version: main

- name: "Set up dotfiles"
  ansible.builtin.copy:
    src: /tmp/dotfiles/
    dest: ~/.config/
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '755'


- name: "Set up background"
  ansible.builtin.copy:
    src: files/background.jpg
    dest: /usr/share/backgrounds/background.jpg
    owner: root
    group: root
    mode: '755'
  become: true

- name: "Install fonts"
  ansible.builtin.get_url:
    url: https://webdraft.hu/fonts/classic-console/fonts/clacon2.ttf
    dest: /usr/share/fonts/truetype/clacon2.ttf
    owner: root
    group: root
    mode: '755'
  become: true

- name: "Set up LightDM"
  ansible.builtin.copy:
    src: files/lightdm/
    dest: /etc/lightdm/
    owner: root
    group: root
    mode: '644'
  become: true

- name: "Enable LightDM service"
  ansible.builtin.systemd:
    name: lightdm
    enabled: true
  become: true

- name: Remove python EXTERNALLY-MANAGED files
  ansible.builtin.shell: |
    find / -name EXTERNALLY-MANAGED 2>/dev/null -exec rm -rf {} \;
  changed_when: false
  become: true

- name: "Create config files for root"
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config"
    dest: /root/.config
    state: link
  become: true
