---
- name: "Clone dotfiles"
  ansible.builtin.git:
    repo: "https://github.com/NLXZ/dotfiles.git"
    dest: "/tmp/dotfiles"
    clone: "yes"
    version: main

- name: "Set up dotfiles"
  ansible.builtin.copy:
    src: /tmp/dotfiles/
    dest: ~/.config/
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '755'

- name: "Set up background"
  ansible.builtin.copy:
    src: files/background.png
    dest: /usr/share/backgrounds/background.png
    owner: root
    group: root
    mode: '755'
  become: true

- name: "Set up NeoVim"
  ansible.builtin.shell: |
    /usr/bin/nvim -c ':PackerSync' +qa
  changed_when: false
  become: true

- name: "Set up LightDM"
  ansible.builtin.copy:
    src: files/lightdm/
    dest: /etc/lightdm/
    owner: root
    group: root
    mode: '644'
  become: true

- name: "Enable LightDM service"
  ansible.builtin.systemd:
    name: lightdm
    enabled: true
  become: true

- name: "Set up config directory for root"
  ansible.builtin.file:
    path: /root/.config
    state: absent
  become: true

- name: "Create config files for root"
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config"
    dest: /root/.config
    state: link
  become: true

- name: "Set up keyboard layout"
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT="us"$'
    line: 'XKBLAYOUT="es"'
  become: true

- name: "Set up Time Zone and NTP"
  ansible.builtin.shell: |
    timedatectl set-timezone Europe/Madrid
    timedatectl set-ntp 1
  changed_when: false
  become: true
