---
- name: "Update"
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"  # full upgrade (you may want to comment this line)
  become: true

- name: "Install packages"
  ansible.builtin.apt:
    pkg:
      - bat
      - beep
      - bloodhound-ce-python
      - bloodyad
      - chisel
      - dmenu
      - docker.io
      - donut
      - feh
      - flameshot
      - fonts-jetbrains-mono
      - fuse
      - fzf
      - gdb
      - gdb-peda
      - ghidra
      - gobuster
      - golang
      - i3blocks
      - jq
      - keepassxc
      - kitty
      - krb5-config
      - krb5-user
      - lftp
      - libpcap-dev
      - libxml2-dev
      - libxslt-dev
      - lsd
      - ltrace
      - lxappearance
      - mingw-w64
      - mono-complete
      - moreutils
      - nishang
      - npm
      - ntpsec-ntpdate
      - obsidian
      - rdate
      - remmina
      - rlwrap
      - rofi
      - seclists
      - sshpass
      - sshuttle
      - strace
      - username-anarchy
      - xsel
  become: true

- name: "Clean up"
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
  become: true
