---
- name: "Update"
  ansible.builtin.apt:
    update_cache: true
    # upgrade: "yes"
  become: true

- name: "Install packages"
  ansible.builtin.apt:
    pkg:
      - bat
      - beep
      - bloodyad
      - chisel
      - dmenu
      - docker.io
      - feh
      - flameshot
      - fonts-jetbrains-mono
      - fuse
      - fzf
      - gdb
      - gdb-peda
      - ghidra
      - gobuster
      - golang
      - i3blocks
      - krb5-user
      - krb5-config
      - jq
      - kitty
      - lftp
      - lsd
      - ltrace
      - lxappearance
      - moreutils
      - netexec
      - npm
      - ntpdate
      - obsidian
      - rdate
      - remmina
      - rofi
      - seclists
      - sshpass
      - strace
      - xsel
  become: true

- name: "Clean up"
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
  become: true
