---
- name: "Set up external packages"
  ansible.builtin.copy:
    src: files/external_packages.sh
    dest: /tmp/external_packages.sh
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '755'

- name: "Install external packages"
  ansible.builtin.script: /tmp/external_packages.sh
