---
- name: "Import package list"
  ansible.builtin.include_vars: git.yml

- name: "Install packages"
  ansible.builtin.get_url:
    url: "{{ item.values() | first }}"
    dest: "/usr/bin/{{ item.keys() | first }}"
    owner: "root"
    group: "root"
    mode: '755'
  become: true
  loop: "{{ install_packages_git }}"
  loop_control:
    label: " {{ item.keys() | first }}"

- name: "Set up packages"
  ansible.builtin.unarchive:
    src: /usr/bin/bloodhound-cli-linux-amd64.tar.gz
    dest: /usr/bin/
    remote_src: yes
